name: qarz_daftar
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  device_info_plus: ^10.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.7
  image_picker: ^1.1.2
  keyboard_dismisser: ^3.0.0
  logger: ^2.4.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.2.13
  url_launcher: ^6.3.0
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  formz: ^0.7.0
  connectivity_plus: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  flutter_inappwebview: ^6.1.0+1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
